apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: registry.redhat.io/rhel10/postgresql-16
          env:
            - name: POSTGRESQL_DATABASE
              value: moviesdb
            - name: POSTGRESQL_USER
              value: devuser
            - name: POSTGRESQL_PASSWORD
              value: devpass
          ports:
            - containerPort: 5432